- name: Modifica el dispositivo de instalacion de Grub
  debconf:
    name: grub-pc
    question: grub-pc/install_devices
    value: /dev/vda1
    vtype: string

- name: Asegurarse que el sistema esta actualizado
  apt: update_cache=yes upgrade=yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Deshabilitando SWAP
  shell: swapoff -a

- name: Deshabilitando SWAP permanentemente desde fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Instalar APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: Instalar docker
  apt:
    name: 
      - docker
      - docker.io
    state: present

- name: Agregar apt-key Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Agregar repositorio de Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Instalar kubelet
  apt:
    name: kubelet
    state: present
    update_cache: true

- name: Instalar kubeadm
  apt:
    name: kubeadm
    state: present