- name: Instalar kubectl
  apt:
    name: kubectl
    state: present
    force: yes

- name: Iniciar el Cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Crear directorio .Kube
  become: yes
  become_user: vagrant
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copiar el admin.conf para el usuario en el directorio .kube
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant

- name: Instalar Pod Network
  become: yes
  become_user: vagrant
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: Generar Token para los workers
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Compartir el Token en variable.
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"